### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by qitia** [qyhdt/campaign-dev-helper#1]
Fantastic tool! Some suggestions as below

- Clean stale logs from those test result folders
- List all .proj/.csproj file in the list for user to choose and open: msbuild /t:slnGen abc.csproj/dirs.proj
- Kill one tool processes by process name lookup.

**Comment by qyhdt** [comment]
published v1.0.7, it has used msbuild /t:slnGen abc.csproj/dirs.proj to open a new project, so that if user did not build first, they also can open a project.
